### ISSUE TITLE
Jenkins slave docker image out of date

### ISSUE THREAD

**Issue by clanstyles** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#80]
I'm experiencing the following error since my cluster update.
```
error: group map[componentconfig:0xc820376e70 extensions:0xc820376ee0 policy:0xc820376f50 authentication.k8s.io:0xc8203770a0 :0xc820376c40 authorization.k8s.io:0xc820376d20 autoscaling:0xc820376d90 batch:0xc820376e00 federation:0xc820376bd0 apps:0xc820376cb0 rbac.authorization.k8s.io:0xc820376fc0] is already registered
```

I've been able to trace it to a most likely problematic kubectl version. The docker slave image must be cached on the "latest" version. Because the latest version is installing a "then latest version" of kubectl, it's now out of date.

What's the proper way across all the machines to update or remove this container?

**Comment by clanstyles** [comment]
I was able to remote the image on the machine that it was spun up on. The next issue I ran into was that it seems to be using:

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

Which 1.3.4 is old. The actual docker image seems to pull from the latest version, but this always loads an older version. I checked the image is tagged latest.

**Comment by pdoreau** [comment]
Indeed. I rebuilt myself copying the [Dockerfile](https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/blob/master/jenkins/docker-slave-image/Dockerfile), pushed to a private repository and used it in my Jenkins configuration. It works well as a temporary workaround before the next official build.

**Comment by abhishekShukla** [comment]
I am new to this stuff. How would I go about resolving this exactly? What Jenkins configuration should I change after pushing the image to a private repository?

**Comment by clanstyles** [comment]
@abhishekShukla After you compile your image to a private repository, go to Jenkins -> Configure -> Images, Containers, Docker image. You should see the image that you can swap out for your own here.

**Comment by abhishekShukla** [comment]
I did that and now my job gets stuck here: 

.
.
.
Still waiting to schedule task
Waiting for next available executor

**Comment by clanstyles** [comment]
Hey @abhishekShukla give it a little time to process. It might need to pull the container the first time and actually spin up an executor. This takes a few minutes for me sometimes.


I would also double check the setting Manage Jenkins -> Manage Nodes -> Click the cog on the right of Master. Make sure that # of executors is set to "0". Additionally, make sure you have enough resources on your cluster to perform the actions.

**Comment by abhishekShukla** [comment]
It seems like I had to name the slave image: "jenkins-k8s-slave" specifically. This solution works now. Thank you @clanstyles and @pdoreau

**Comment by ichiaohsu** [comment]
@abhishekShukla Thank you for the tip! I found the Dockerfile and built my version of jnlp-slave image but keep fail and get error java.nio.channels.ClosedChannelException. I succeeded after change the image name to "jenkins-k8s-slave". Thank you so much! 

But I am so curious about this: Is the docker image with name other than "jenkins-k8s-slave" would be blocked by jenkins master?

**Comment by abhishekShukla** [comment]
@ichiaohsu I can't seem to figure out where that dependency comes from. As I mentioned, I am new at this.

**Comment by viglesiasce** [comment]
This has been fixed in the latest build of the jenkins-slave-image image. There should be no dependency by the kubernetes plugin on the name of the image it uses.

**Comment by KJlmfe** [comment]
@viglesiasce 

I follow this tutorial https://cloud.google.com/solutions/configuring-jenkins-kubernetes-engine
and use `gcr.io/cloud-solutions-images/jenkins-k8s-slave`, but it still doesn't work.

Finally, I change the image name to "jenkins-k8s-slave" and it works.

It seems that this bug is not fixed in the latest image?
